{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bayestools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BayesTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BayesTools/BayesTools_{{ version }}.tar.gz
  sha256: 25214d20e5a1698d76bde30b084d130ab57e105d9c16f0c47a0bec3e07287265

build:
  ## jags is not available on windows
  skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bridgesampling
    - r-coda
    - r-extradistr
    - r-ggplot2
    - r-runjags
    - r-rdpack
  run:
    - r-base
    - r-bridgesampling
    - r-coda
    - r-extradistr
    - r-ggplot2
    - r-runjags
    - r-rdpack

test:
  commands:
    - $R -e "library('BayesTools')"           # [not win]
    - "\"%R%\" -e \"library('BayesTools')\""  # [win]

about:
  home: https://fbartos.github.io/BayesTools/
  license: GPL-3.0-only
  summary: Provides tools for conducting Bayesian analyses. The package contains functions for creating a wide range of prior distribution objects, mixing posterior samples from 'JAGS' and 'Stan' models, plotting posterior distributions, and etc... The tools for working with prior distribution span from visualization, generating
    'JAGS' and 'bridgesampling' syntax to basic functions such as rng, quantile, and distribution functions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
