{% set version = "0.2.22" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bayestools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BayesTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BayesTools/BayesTools_{{ version }}.tar.gz
  sha256: e80abb519ec62fe677cbf697fff2d552af201d6169d1a51e6bcc2a780e82c782

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rdpack
    - r-bridgesampling
    - r-coda
    - r-extradistr
    - r-ggplot2
    - r-mvtnorm
    - r-rjags
    - r-runjags
  run:
    - r-base
    - r-rdpack
    - r-bridgesampling
    - r-coda
    - r-extradistr
    - r-ggplot2
    - r-mvtnorm
    - r-rjags
    - r-runjags

test:
  commands:
    - $R -e "library('BayesTools')"           # [not win]
    - "\"%R%\" -e \"library('BayesTools')\""  # [win]

about:
  home: https://fbartos.github.io/BayesTools/
  license: GPL-3.0-only
  summary: Provides tools for conducting Bayesian analyses. The package contains functions for creating a wide range of prior distribution objects, mixing posterior samples from 'JAGS' and 'Stan' models, plotting posterior distributions, and etc... The tools for working with prior distribution span from visualization, generating
    'JAGS' and 'bridgesampling' syntax to basic functions such as rng, quantile, and distribution functions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
